### Create a new project

POST http://localhost:3333/api/v1/projects
Content-Type: application/json

{
}

### List all projects

GET http://localhost:3333/api/v1/projects

### Show a unique project

GET http://localhost:3333/api/v1/projects/1

### Update complete or partially a project

PATCH http://localhost:3333/api/v1/projects/1
Content-Type: application/json

{
  "title": "Test",
  "description": "Test"
}

### Destroy a unique project

DELETE  http://localhost:3333/api/v1/projects/1