### Create a new project

POST http://localhost:3001/project
Content-Type: application/json

{
  "title": "Test",
  "description": "Description",
  "image": "image-url",
  "sourceCode": "code-url"
}

### List all projects

GET http://localhost:3001/project

### Show a unique project

GET http://localhost:3001/project/ffefcf8e-3934-4bbd-9ab7-46288c598788

### Update complete or partially a project

PATCH http://localhost:3001/project/
Content-Type: application/json

{
  "title": "Test 4",
  "description": "Description 4"
}

### Destroy a unique project

DELETE  http://localhost:3001/project/83054834-926b-4882-ab83-a56912b77479